spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_app
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

app:
  jwt:
    secret: 1234567890123456789012345678901234567890123456789012345678901234
    expiration-ms: 86400000
