spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_app
    username: blog_user
    password: blog_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
server:
  port: 8080
app:
  jwt:
    secret: "this-is-a-very-long-secret-key-change-in-production-123456789"
    expiration-ms: 86400000
